### ISSUE TITLE
Some functions do not leverage elm TCO

### ISSUE THREAD

**Issue by atdixon** [the-sett/lazy-list#5]
From the REPL:

```
> Seq.dropWhile (\_ -> True) (Seq.repeat 1)
RangeError: Maximum call stack size exceeded
```

This should instead infinitely loop with no call stack explosion.

Other functions may suffer from this, as well (`filterMap`, `keepIf`, ...more?).

This is related to https://github.com/elm/compiler/issues/1770 ; the simple fix is to remove the `<|` operator in favor of direct function application; then elm TCO will kick-in.

**Comment by rupertlssmith** [comment]
Thanks, will take a look at that.

The other pull requests have been merged and published as 1.0.0 BTW. Thanks for making those too.
